version: '3.1'

services:

  db:
    image: postgres:latest
    volumes:
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: Catalog
    ports: 
      - 5432:5432
